Tasks/LittleFashion/LittleFashion/LittleFashion.MVC/Areas/admin/Controllers/CrudController.cs
using LittleFashion.BL.Models;
using LittleFashion.BL.Services;
using Microsoft.AspNetCore.Mvc;

namespace LittleFashion.MVC.Areas.admin.Controllers;

[Area("Admin")]
public class CrudController : Controller
{
    private readonly ProductrModelService _productrModelService;

    public CrudController()
    {
        _productrModelService = new ProductrModelService();
    }

    public IActionResult Index()
    {
        List<ProductModel> getAllProd = _productrModelService.GetAllProd();

        return View(getAllProd);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(ProductModel product)
    {
        _productrModelService.CreateProd(product);
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public IActionResult Delete(int id)
    {
        _productrModelService.DeleteProd(id);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult Info(int id)
    {
        ProductModel productModel = _productrModelService.GetProductById(id);
        return View(productModel);
    }
}

Tasks/LittleFashion/LittleFashion/LittleFashion.MVC/Areas/admin/Controllers/DashboardController.cs
using LittleFashion.BL.Models;
using LittleFashion.BL.Services;
using Microsoft.AspNetCore.Mvc;

namespace LittleFashion.MVC.Areas.admin.Controllers
{
    [Area("Admin")]

    public class DashboardController : Controller
    {

        private readonly ProductrModelService _productrModelService;

        public DashboardController()
        {
            _productrModelService = new ProductrModelService();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Tasks/LittleFashion/LittleFashion/LittleFashion.MVC/Controllers/HomeController.cs
using LittleFashion.BL.Models;
using LittleFashion.BL.Services;
using Microsoft.AspNetCore.Mvc;

namespace LittleFashion.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProductrModelService _productrModelService;

        public HomeController()
        {
            _productrModelService = new ProductrModelService();
        }

        public IActionResult Index()
        {
            List<ProductModel> getAllProd = _productrModelService.GetAllProd();

            return View(getAllProd);
        }
    }
}

Tasks/LittleFashion/LittleFashion/LittleFashion.MVC/Areas/admin/Views/Crud/Create.cshtml
@using LittleFashion.BL.Models
@model ProductModel

<form asp-area="Admin" asp-controller="Crud" asp-action="Create" enctype="multipart/form-data" style="padding: 150px;">
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Category</label>
        <input asp-for="Category" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Choose Image</label>
        <input asp-for="ImgFile" type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Title</label>
        <input asp-for="Title" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Desc</label>
        <input asp-for="Desc" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Price</label>
        <input asp-for="Price" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Tasks/LittleFashion/LittleFashion/LittleFashion.MVC/Areas/admin/Views/Crud/Index.cshtml
@model List<ProductModel>

<div id="layoutSidenav_content" style="padding: 40px;">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Dashboard</h1>

            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">
                    <a asp-area="Admin" asp-controller="Crud" asp-action="Create">Create Product</a>
                </li>
            </ol>

            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    DataTable Example
                </div>
                <div class="card-body">
                    <table id="datatablesSimple" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Category</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Desc</th>
                                <th>Price</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ProductModel item in Model)
                            {
                                <tr>
                                    <td>@item.Category</td>
                                    <td><img src="~/assets/uploadedImages/@item.ImgPath" alt="Alternate Text" width="100" /></td>
                                    <td>@item.Title</td>
                                    <td>@item.Desc</td>
                                    <td>@item.Price</td>
                                    <td>
                                        <div class="btn-group" role="group" style="display: flex; gap: 20px;">
                                            <a asp-area="Admin" asp-controller="Crud" asp-action="Info" asp-route-id="@item.Id" class="btn btn-info btn-sm">Info</a>
                                            <a asp-area="Admin" asp-controller="Crud" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Update</a>
                                            <form asp-area="Admin" asp-controller="Crud" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </main>
</div>

Tasks/LittleFashion/LittleFashion/LittleFashion.MVC/Areas/admin/Views/Crud/Info.cshtml
<div class="col-lg-4 col-12 mb-3">
    <div class="product-thumb">
        <a href="product-detail.html">
            <img src="@Model.ImgPath" class="img-fluid product-image" alt="">
        </a>

        <div class="product-top d-flex">
            <span class="product-alert me-auto">@Model.Category</span>

            <a href="#" class="bi-heart-fill product-icon"></a>
        </div>

        <div class="product-info d-flex">
            <div>
                <h5 class="product-title mb-0">
                    <a href="product-detail.html" class="product-title-link">@Model.Title</a>
                </h5>

                <p class="product-p">@Model.Desc</p>
            </div>

            <small class="product-price text-muted ms-auto mt-auto mb-5">@Model.Price</small>
        </div>
    </div>
</div>